name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint || true
      - name: Test
        run: pnpm test || echo "No tests found"
      - name: Build
        run: pnpm build 